chore: install yarn deps in production mode
packit/dashboard pull request #329
Opened 2023-09-11 16:20 UTC by mfocko

From the yarn docs:

> Yarn will not install any package listed in `devDependencies` if the
> `NODE_ENV` environment variable is set to `production`. Use this flag
> to instruct Yarn to ignore `NODE_ENV` and take its production-or-not
> status from this flag instead.

This should ensure that no development dependencies, such as `surge`, are installed at all in the image that we use for deployments.

Yet another follow-up to the vulnerability report for the MP+ deployment.

2023-09-11 17:08 UTC, SpyTec requested changes

2023-09-11 17:51 UTC, mfocko commented on files/ansible/recipe.yaml
> +        cmd: yarn install --production
It should be fine: https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install

2023-09-11 17:52 UTC, mfocko commented on files/ansible/recipe.yaml
> +        cmd: yarn install --production
though I'm not against being explicit

2023-09-11 18:13 UTC, jpopelka approved these changes

2023-09-12 11:13 UTC, lbarcziova approved these changes

2023-09-12 11:50 UTC, mfocko commented
@.SpyTec Sorry for the additional review request, but with the requested changes you blocked merging 😄

2023-09-14 13:50 UTC, merged

2023-09-15 15:45 UTC, SpyTec commented
> @.SpyTec Sorry for the additional review request, but with the requested changes you blocked merging 😄

There is a way to dismiss review requests just above the merge button :D