Adjust to Anitya related API changes
packit/dashboard pull request #439
Opened 2024-08-19 06:19 UTC by lbarcziova

Related to packit/packit-service#2203
Related to packit/packit-service#2202

2024-08-19 10:36 UTC, Venefilyn requested changes

2024-08-19 10:36 UTC, Venefilyn commented on frontend/src/components/trigger/TriggerLink.tsx
We could do something like this to split it up and assert types. That way we require usage of `<TriggerSuffix>` to always provide a valid `repo_name` and `repo_namespace` combo or a valid `anitya_*` type. I checked a bunch of usages of `<TriggerLink>` and `<TriggerSuffix />` and it doesn't complain, but some stuff needs to be changed

<details>
<summary>suggested change in TriggerLink.tsx</summary>

```typescript
interface TriggerSuffixInterface {
  branch_name?: string | null;
  issue_id?: number | null;
  pr_id?: number | null;
  release?: string | null;
}

interface TriggerSuffixRepo extends TriggerSuffixInterface {
  repo_name: string;
  repo_namespace: string;
}

interface TriggerSuffixAnitya extends TriggerSuffixInterface {
  anitya_project_name: string;
  anitya_version: string;
  anitya_package: string;
}

type TriggerSuffixProps = {
  trigger: TriggerSuffixRepo | TriggerSuffixAnitya;
};

const TriggerSuffix: React.FC<TriggerSuffixProps> = ({ trigger }) => {
  // set suffix to be either PR ID or Branch Name depending on trigger
  let jobSuffix = "";

  if ("anitya_version" in trigger) {
    jobSuffix = `#version:${trigger.anitya_version}`;
    return (
      <>
        {trigger.anitya_project_name}/{jobSuffix}
      </>
    );
  } else if (trigger.pr_id) {
    jobSuffix = `#${trigger.pr_id}`;
  } else if (trigger.issue_id) {
    jobSuffix = `#${trigger.issue_id}`;
  } else if (trigger.branch_name) {
    jobSuffix = `:${trigger.branch_name}`;
  } else if (trigger.release) {
    jobSuffix = `#release:${trigger.release}`;
  }

  return (
    <>
      {trigger.repo_namespace}/{trigger.repo_name}
      {jobSuffix}
    </>
  );
};
```
</details>

And we need to change all `apiDefinitions.ts` `antiya_*` properties to be from `unknown | null` to `string | null`

2024-08-19 11:54 UTC, lbarcziova commented on frontend/src/components/trigger/TriggerLink.tsx
> +    );
yes, that's right

2024-08-20 10:20 UTC, lbarcziova commented on frontend/src/components/trigger/TriggerLink.tsx
with your suggestion, the `("anitya_version" in trigger)` was always evaluated as `true`, so I changed it a little bit so locally it works, but I am not really sure if this is correct, PTAL :D

2024-08-20 11:14 UTC, Venefilyn commented on frontend/src/components/trigger/TriggerLink.tsx
Okay figured it out. The suggestion you added was something I thought would work but evidently you need to define that somewhere, which makes it a bit more difficult. I did however find a way to get it to work correctly as far as I can tell

```
interface TriggerSuffixGitRepo extends TriggerSuffixInterface {
  repo_name: string;
  repo_namespace: string;
  anitya_project_name?: string | null;
  anitya_version?: string | null;
  anitya_package?: string | null;
}

interface TriggerSuffixAnityaProject extends TriggerSuffixInterface {
  anitya_project_name: string;
  anitya_version: string;
  anitya_package: string;
  repo_name?: string | null;
  repo_namespace?: string | null;
}

type TriggerSuffixProps = {
  trigger: TriggerSuffixGitRepo | TriggerSuffixAnityaProject;
};

const TriggerSuffix: React.FC<TriggerSuffixProps> = ({ trigger }) => {
  let jobSuffix = "";

  if (isAnityaTrigger(trigger)) {
    jobSuffix = `#version:${trigger.anitya_version}`;
    return (
      <>
        {trigger.anitya_project_name}/{jobSuffix}
      </>
    );
  } else if (trigger.pr_id) {
    jobSuffix = `#${trigger.pr_id}`;
  } else if (trigger.issue_id) {
    jobSuffix = `#${trigger.issue_id}`;
  } else if (trigger.branch_name) {
    jobSuffix = `:${trigger.branch_name}`;
  } else if (trigger.release) {
    jobSuffix = `#release:${trigger.release}`;
  }

  return (
    <>
      {trigger.repo_namespace}/{trigger.repo_name}
      {jobSuffix}
    </>
  );
};

function isAnityaTrigger(trigger: TriggerSuffixProps["trigger"]): trigger is TriggerSuffixAnityaProject {
  return typeof trigger.anitya_version === "string" &&
    trigger.anitya_version.length > 0
}
```

It has to do with the last bit in the code, which is a [type guard](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)

2024-08-21 08:46 UTC, lbarcziova commented on frontend/src/components/trigger/TriggerLink.tsx
thanks, added!

2024-08-21 08:47 UTC, lbarcziova commented
regarding the icons, I was choosing between 

![Snímka obrazovky z 2024-08-21 10-44-31](https://github.com/user-attachments/assets/fe7714cf-808e-465a-8dfd-d8577f6eb684)
![Snímka obrazovky z 2024-08-21 10-44-09](https://github.com/user-attachments/assets/5ff446b7-cb2b-4d78-abe2-b26a9ad8c70c)

let me know which one you like more (even some other from [here](https://www.patternfly.org/design-foundations/icons/))

2024-08-21 13:25 UTC, Venefilyn approved these changes
LGTM, just the icon selection left then :D

2024-08-21 14:21 UTC, mfocko commented
> regarding the icons, I was choosing between
> 
> ![Snímka obrazovky z 2024-08-21 10-44-31](https://private-user-images.githubusercontent.com/49026743/359823342-fe7714cf-808e-465a-8dfd-d8577f6eb684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTAzNDUsIm5iZiI6MTcyNDI1MDA0NSwicGF0aCI6Ii80OTAyNjc0My8zNTk4MjMzNDItZmU3NzE0Y2YtODA4ZS00NjVhLThkZmQtZDg1NzdmNmViNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYzdjMzZjNTI2MTBmMDlhZTFiOTRkMWVkMDlkYWI5MzNjMjA2YmFlMDEwNDRkNGY3NmU3MmMxZDNhZDhiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ql-GrOa9URqQH2FyRTd0bTjQZAa2l4kxowFB3tngJrE) ![Snímka obrazovky z 2024-08-21 10-44-09](https://private-user-images.githubusercontent.com/49026743/359823352-5ff446b7-cb2b-4d78-abe2-b26a9ad8c70c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTAzNDUsIm5iZiI6MTcyNDI1MDA0NSwicGF0aCI6Ii80OTAyNjc0My8zNTk4MjMzNTItNWZmNDQ2YjctY2IyYi00ZDc4LWFiZTItYjI2YTlhZDhjNzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMDA2NTViZTQ5ZTRhMjUxNjhkMzU3MmI4NGJiOWU4OTJlMzgzNmYxNjJlNzQ4NDc3ZmFiY2FiZTNjNDdmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VovqTzBIOYFBygSWfTEO8y0Reb8WMpaD0KtBTGK4l-E)
> 
> @packit/the-packit-team , let me know which one you like more (even some other from [here](https://www.patternfly.org/design-foundations/icons/))

first :)

2024-08-21 14:40 UTC, merged

2024-08-21 16:03 UTC, Venefilyn commented on frontend/src/apiDefinitions.ts
> -  antiya_package: unknown | null;
Just saw I made a typo that you fixed here. Anitya is really bad for my dyslexia

2024-08-27 21:38 UTC, lachmanfrantisek commented
Looks like the pipeline view does not like this change..;(

![image](https://github.com/user-attachments/assets/8313ef03-8cee-49a6-8bdc-08b13c2d7e07)

2024-09-02 11:56 UTC, lbarcziova commented
@lachmanfrantisek will have a look into it today, thanks for letting me know.

2024-09-02 12:04 UTC, Venefilyn commented
@lbarcziova I got back from PTO today and can also take a look if you want, just ping me if so

2024-09-02 13:20 UTC, lbarcziova commented
@Venefilyn no problem, I also just got from the PTO, but opened #446 for this. Though if I checked correctly, the exception was not related to changes in this PR at all, it looks like just runs occasionally missing the trigger in the response.