Skip pipelines without triggers from displaying
packit/dashboard pull request #446
Opened 2024-09-02 13:18 UTC by lbarcziova

2024-09-02 14:38 UTC, Venefilyn reviewed
Feels strange that triggers can be undefined. Could you update the `apiDefinitions.ts` as well? It might catch a few more errors we should catch, like in the pipeline detail

2024-09-02 18:26 UTC, Venefilyn requested changes

2024-09-02 18:26 UTC, Venefilyn commented on frontend/src/components/pipeline/PipelinesTable.tsx
> +        .map((run) => <PipelinesTableTr key={run.merged_run_id} run={run} />),
Checked into things a bit more, I think we can do better by displaying the rows but simply updating the `<PipelinesTableTr>`:

```tsx
<strong>
  {run.trigger && "project_url" in run.trigger ? (
    <ForgeIcon url={run.trigger.project_url} />
  ) : (
    <ForgeIconByForge />
  )}{" "}
  <Link to={`/pipeline/${run.merged_run_id}`}>
    {run.trigger && "project_url" in run.trigger ? (
      <>
        <TriggerSuffix trigger={run.trigger} />
      </>
    ) : (
      <>{run.merged_run_id}</>
    )}
  </Link>
</strong>
```

2024-09-03 05:40 UTC, lbarcziova commented on frontend/src/components/pipeline/PipelinesTable.tsx
> +        .map((run) => <PipelinesTableTr key={run.merged_run_id} run={run} />),
that was my initial solution, but I believe these are really occasionally malformed data that should not be displayed at all

2024-09-03 10:40 UTC, Venefilyn approved these changes
LGTM

2024-09-03 10:40 UTC, Venefilyn commented on frontend/src/components/pipeline/PipelinesTable.tsx
> +        .map((run) => <PipelinesTableTr key={run.merged_run_id} run={run} />),
Ack! I think this should be fixed at the service level as well to ensure this won't happen

2024-09-03 10:41 UTC, merged

2024-09-04 09:27 UTC, lachmanfrantisek commented
@lbarcziova ,  @Venefilyn Thanks both of you!