Fix deps installation in makefile and adjust docs
packit/dashboard pull request #456
Opened 2024-09-26 10:03 UTC by mfocko

2024-09-26 10:26 UTC, Venefilyn requested changes

2024-09-26 10:26 UTC, Venefilyn commented on Makefile
> +
Note sure which version but we can install NodeJS>16 to get corepack
```suggestion
	sudo dnf -y install python3-flask python3-flask-cors python3-flask-talisman nodejs

```

2024-09-26 10:26 UTC, Venefilyn commented on CONTRIBUTING.md
> +guide to set up a directory for `npm` in your home directory.
If it's included in NodeJS v16 and above it should just work without issue so seems unnecessary in that case

2024-09-26 13:02 UTC, mfocko commented on Makefile
> +
```
mfocko@ampere 
~ % node --version
v20.17.0
mfocko@ampere 
~ % corepack
zsh: corepack: command not found...
```

uhh…

2024-09-26 14:31 UTC, Venefilyn commented on Makefile
> +
Huh..

We can change it around to just install pnpm. `dnf install pnpm`. Might be better

2024-10-01 11:32 UTC, Venefilyn commented on Makefile
> +
Try this
```suggestion
	sudo dnf -y install python3-flask python3-flask-cors python3-flask-talisman pnpm
```
```
📦[spytec@fedora-rawhide]~% dnf search pnpm --showduplicates
Updating and loading repositories:
Repositories loaded.
Matched fields: name (exact)
 pnpm-0:9.11.0-1.fc42.noarch: Fast, disk space efficient package manager
```

2024-10-01 12:13 UTC, mfocko commented
recheck

2024-10-04 13:22 UTC, Venefilyn commented on CONTRIBUTING.md
> +guide to set up a directory for `npm` in your home directory.
If dnf install works we can probably remove this

2024-10-27 13:42 UTC, lbarcziova approved these changes
thanks!

2024-10-28 13:43 UTC, Venefilyn requested changes

2024-10-28 13:43 UTC, Venefilyn commented on CONTRIBUTING.md
> +guide to set up a directory for `npm` in your home directory.
```suggestion
`make install-dependencies` automatically installs python dependencies and `pnpm`.
In case the `pnpm` installation fails, follow [this](https://pnpm.io/installation) guide for
different installation options.
```

2024-10-28 14:40 UTC, Venefilyn approved these changes

2024-10-28 14:40 UTC, merged